#!/usr/bin/env bash
set -euo

if [ ! -d 'sdk' ]; then
    mkdir sdk
    curl -L https://aka.ms/dotnet/8.0.1xx/daily/dotnet-sdk-linux-x64.tar.gz | tar -xz -C ./sdk
fi

export DOTNET_ROOT="/sea/sdk"
export PATH="$DOTNET_ROOT:$PATH"

if [ ! -d '.nuget' ]; then
    export RestorePackagesPath="/sea/.nuget/packages"
    dotnet restore sea.csproj
fi

pushd sea

rm -rf obj
rm sea sea.dll sea.ilc.rsp sea.o sea.pdb || true

/sea/sdk/dotnet exec \
    "/sea/sdk/sdk/8.0.100-preview.2.23116.17/Roslyn/bincore/csc.dll" \
    /noconfig \
    /unsafe- \
    /checked- \
    "/nowarn:1701,1702,IL2121,1701,1702" \
    /fullpaths \
    /nostdlib+ \
    /platform:x64 \
    /errorreport:prompt \
    /warn:8 \
    "/define:TRACE;DEBUG;NET;NET8_0;NETCOREAPP;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NET7_0_OR_GREATER;NET8_0_OR_GREATER;NETCOREAPP1_0_OR_GREATER;NETCOREAPP1_1_OR_GREATER;NETCOREAPP2_0_OR_GREATER;NETCOREAPP2_1_OR_GREATER;NETCOREAPP2_2_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER" \
    /highentropyva+ \
    /nullable:enable \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/Microsoft.CSharp.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/Microsoft.VisualBasic.Core.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/Microsoft.VisualBasic.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/Microsoft.Win32.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/Microsoft.Win32.Registry.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/mscorlib.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/netstandard.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.AppContext.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Buffers.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Collections.Concurrent.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Collections.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Collections.Immutable.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Collections.NonGeneric.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Collections.Specialized.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ComponentModel.Annotations.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ComponentModel.DataAnnotations.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ComponentModel.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ComponentModel.EventBasedAsync.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ComponentModel.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ComponentModel.TypeConverter.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Configuration.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Console.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Core.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Data.Common.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Data.DataSetExtensions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Data.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.Contracts.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.Debug.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.DiagnosticSource.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.FileVersionInfo.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.Process.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.StackTrace.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.TextWriterTraceListener.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.Tools.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.TraceSource.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Diagnostics.Tracing.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Drawing.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Drawing.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Dynamic.Runtime.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Formats.Asn1.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Formats.Tar.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Globalization.Calendars.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Globalization.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Globalization.Extensions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.Compression.Brotli.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.Compression.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.Compression.FileSystem.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.Compression.ZipFile.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.FileSystem.AccessControl.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.FileSystem.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.FileSystem.DriveInfo.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.FileSystem.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.FileSystem.Watcher.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.IsolatedStorage.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.MemoryMappedFiles.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.Pipes.AccessControl.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.Pipes.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.IO.UnmanagedMemoryStream.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Linq.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Linq.Expressions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Linq.Parallel.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Linq.Queryable.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Memory.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Http.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Http.Json.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.HttpListener.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Mail.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.NameResolution.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.NetworkInformation.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Ping.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Quic.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Requests.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Security.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.ServicePoint.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.Sockets.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.WebClient.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.WebHeaderCollection.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.WebProxy.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.WebSockets.Client.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Net.WebSockets.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Numerics.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Numerics.Vectors.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ObjectModel.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.DispatchProxy.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.Emit.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.Emit.ILGeneration.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.Emit.Lightweight.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.Extensions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.Metadata.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Reflection.TypeExtensions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Resources.Reader.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Resources.ResourceManager.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Resources.Writer.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.CompilerServices.Unsafe.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.CompilerServices.VisualC.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Extensions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Handles.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.InteropServices.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.InteropServices.JavaScript.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.InteropServices.RuntimeInformation.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Intrinsics.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Loader.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Numerics.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Serialization.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Serialization.Formatters.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Serialization.Json.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Serialization.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Runtime.Serialization.Xml.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.AccessControl.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Claims.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.Algorithms.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.Cng.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.Csp.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.Encoding.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.OpenSsl.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.Primitives.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Cryptography.X509Certificates.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Principal.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.Principal.Windows.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Security.SecureString.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ServiceModel.Web.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ServiceProcess.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Text.Encoding.CodePages.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Text.Encoding.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Text.Encoding.Extensions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Text.Encodings.Web.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Text.Json.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Text.RegularExpressions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Channels.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Overlapped.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Tasks.Dataflow.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Tasks.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Tasks.Extensions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Tasks.Parallel.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Thread.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.ThreadPool.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Threading.Timer.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Transactions.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Transactions.Local.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.ValueTuple.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Web.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Web.HttpUtility.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Windows.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.Linq.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.ReaderWriter.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.Serialization.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.XDocument.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.XmlDocument.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.XmlSerializer.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.XPath.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/System.Xml.XPath.XDocument.dll \
    /reference:/sea/sdk/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23115.9/ref/net8.0/WindowsBase.dll \
    /debug+ \
    /debug:portable \
    /filealign:512 \
    /optimize- \
    /out:sea.dll \
    /target:exe \
    /warnaserror- \
    /utf8output \
    /deterministic+ \
    /warnaserror+:NU1605,SYSLIB0011 \
    Program.cs

"/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/tools/ilc" \
    sea.dll \
    -o:sea.o \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/WindowsBase.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/Microsoft.CSharp.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/Microsoft.VisualBasic.Core.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/Microsoft.VisualBasic.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/Microsoft.Win32.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/Microsoft.Win32.Registry.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/mscorlib.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/netstandard.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.AppContext.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Buffers.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Collections.Concurrent.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Collections.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Collections.Immutable.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Collections.NonGeneric.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Collections.Specialized.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ComponentModel.Annotations.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ComponentModel.DataAnnotations.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ComponentModel.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ComponentModel.EventBasedAsync.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ComponentModel.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ComponentModel.TypeConverter.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Configuration.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Console.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Core.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Data.Common.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Data.DataSetExtensions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Data.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.Contracts.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.Debug.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.DiagnosticSource.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.FileVersionInfo.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.Process.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.StackTrace.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.TextWriterTraceListener.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.Tools.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.TraceSource.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Diagnostics.Tracing.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Drawing.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Drawing.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Dynamic.Runtime.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Formats.Asn1.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Formats.Tar.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Globalization.Calendars.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Globalization.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Globalization.Extensions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.Compression.Brotli.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.Compression.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.Compression.FileSystem.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.Compression.ZipFile.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.FileSystem.AccessControl.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.FileSystem.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.FileSystem.DriveInfo.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.FileSystem.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.FileSystem.Watcher.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.IsolatedStorage.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.MemoryMappedFiles.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.Pipes.AccessControl.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.Pipes.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.IO.UnmanagedMemoryStream.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Linq.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Linq.Expressions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Linq.Parallel.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Linq.Queryable.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Memory.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Http.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Http.Json.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.HttpListener.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Mail.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.NameResolution.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.NetworkInformation.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Ping.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Quic.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Requests.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Security.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.ServicePoint.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.Sockets.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.WebClient.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.WebHeaderCollection.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.WebProxy.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.WebSockets.Client.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Net.WebSockets.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Numerics.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Numerics.Vectors.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ObjectModel.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Private.DataContractSerialization.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Private.Uri.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Private.Xml.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Private.Xml.Linq.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.DispatchProxy.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.Emit.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.Emit.ILGeneration.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.Emit.Lightweight.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.Extensions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.Metadata.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Reflection.TypeExtensions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Resources.Reader.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Resources.ResourceManager.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Resources.Writer.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.CompilerServices.Unsafe.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.CompilerServices.VisualC.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Extensions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Handles.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.InteropServices.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.InteropServices.JavaScript.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.InteropServices.RuntimeInformation.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Intrinsics.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Loader.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Numerics.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Serialization.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Serialization.Formatters.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Serialization.Json.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Serialization.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Runtime.Serialization.Xml.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.AccessControl.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Claims.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.Algorithms.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.Cng.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.Csp.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.Encoding.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.OpenSsl.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.Primitives.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Cryptography.X509Certificates.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Principal.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.Principal.Windows.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Security.SecureString.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ServiceModel.Web.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ServiceProcess.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Text.Encoding.CodePages.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Text.Encoding.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Text.Encoding.Extensions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Text.Encodings.Web.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Text.Json.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Text.RegularExpressions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Channels.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Overlapped.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Tasks.Dataflow.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Tasks.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Tasks.Extensions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Tasks.Parallel.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Thread.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.ThreadPool.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Threading.Timer.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Transactions.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Transactions.Local.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.ValueTuple.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Web.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Web.HttpUtility.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Windows.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.Linq.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.ReaderWriter.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.Serialization.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.XDocument.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.XmlDocument.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.XmlSerializer.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.XPath.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/System.Xml.XPath.XDocument.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/WindowsBase.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/System.Private.CoreLib.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/System.Private.DisabledReflection.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/System.Private.Reflection.Execution.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/System.Private.StackTraceMetadata.dll \
    -r:/sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/System.Private.TypeLoader.dll \
    --targetos:linux \
    --targetarch:x64 \
    --dehydrate \
    -g \
    --initassembly:System.Private.CoreLib \
    --initassembly:System.Private.StackTraceMetadata \
    --initassembly:System.Private.TypeLoader \
    --initassembly:System.Private.Reflection.Execution \
    --appcontextswitch:Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability=true \
    --appcontextswitch:System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization=false \
    --appcontextswitch:System.Diagnostics.Tracing.EventSource.IsSupported=false \
    --appcontextswitch:System.Resources.ResourceManager.AllowCustomResourceTypes=false \
    --appcontextswitch:System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false \
    --appcontextswitch:System.Runtime.InteropServices.EnableConsumingManagedCodeFromNativeHosting=false \
    --appcontextswitch:System.Runtime.InteropServices.EnableCppCLIHostActivation=false \
    --appcontextswitch:System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=false \
    --appcontextswitch:System.StartupHookProvider.IsSupported=false \
    --appcontextswitch:System.Threading.Thread.EnableAutoreleasePool=false \
    --appcontextswitch:System.Text.Encoding.EnableUnsafeUTF7Encoding=false \
    --appcontextswitch:RUNTIME_IDENTIFIER=linux-x64 \
    --directpinvoke:libSystem.Native \
    --directpinvoke:libSystem.Globalization.Native \
    --directpinvoke:libSystem.IO.Compression.Native \
    --directpinvoke:libSystem.Net.Security.Native \
    --directpinvoke:libSystem.Security.Cryptography.Native.OpenSsl \
    --feature:Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability=true \
    --feature:System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization=false \
    --feature:System.Diagnostics.Tracing.EventSource.IsSupported=false \
    --feature:System.Resources.ResourceManager.AllowCustomResourceTypes=false \
    --feature:System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false \
    --feature:System.Runtime.InteropServices.EnableConsumingManagedCodeFromNativeHosting=false \
    --feature:System.Runtime.InteropServices.EnableCppCLIHostActivation=false \
    --feature:System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=false \
    --feature:System.StartupHookProvider.IsSupported=false \
    --feature:System.Threading.Thread.EnableAutoreleasePool=false \
    --feature:System.Text.Encoding.EnableUnsafeUTF7Encoding=false \
    --stacktracedata \
    --scanreflection \
    --nowarn:"1701;1702;IL2121;1701;1702" \
    --singlewarn \
    --root:sea.dll \
    --nosinglewarnassembly:sea \
    --resilient \
    --feature:System.Linq.Expressions.CanCompileToIL=false \
    --feature:System.Linq.Expressions.CanEmitObjectArrayDelegate=false \
    --feature:System.Linq.Expressions.CanCreateArbitraryDelegates=false

clang sea.o \
    -o sea \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/libbootstrapper.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/libRuntime.WorkstationGC.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/libeventpipe-disabled.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/libstdc++compat.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/sdk/libnumasupportdynamic.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/libSystem.Native.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/libSystem.Globalization.Native.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/libSystem.IO.Compression.Native.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/libSystem.Net.Security.Native.a \
    /sea/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0-preview.2.23116.1/framework/libSystem.Security.Cryptography.Native.OpenSsl.a \
    -g \
    -Wl,-rpath,'$ORIGIN' \
    -Wl,--build-id=sha1 \
    -Wl,--as-needed \
    -pthread \
    -ldl \
    -lz \
    -lrt \
    -lm \
    -pie \
    -Wl,-pie \
    -Wl,-z,relro \
    -Wl,-z,now \
    -Wl,--discard-all \
    -Wl,--gc-sections

./sea

popd